"""initial schema

Revision ID: 0a192feae12b
Revises: 
Create Date: 2026-06-11 15:42:45.510126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a192feae12b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('prediction_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_predictions_created', 'predictions', ['created_at'], unique=False)
    op.create_index('idx_predictions_risk_level', 'predictions', ['risk_level'], unique=False)
    op.create_index('idx_predictions_user', 'predictions', ['user_id'], unique=False)
    op.create_table('patient_inputs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prediction_id', sa.Uuid(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('glucose', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('blood_pressure', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('medications_count', sa.Integer(), nullable=True),
    sa.Column('previous_admissions', sa.Integer(), nullable=True),
    sa.Column('hospital_stay_days', sa.Integer(), nullable=True),
    sa.Column('bmi', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id')
    )
    op.create_table('shap_explanations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prediction_id', sa.Uuid(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('feature_value', sa.String(length=255), nullable=True),
    sa.Column('shap_value', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('impact_direction', sa.String(length=20), nullable=True),
    sa.Column('importance_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shap_explanations_prediction', 'shap_explanations', ['prediction_id'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prediction_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('original_risk', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('simulated_risk', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('delta_risk', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('simulation_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_simulations_prediction', 'simulations', ['prediction_id'], unique=False)
    op.create_table('simulation_inputs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('simulation_id', sa.Uuid(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('original_value', sa.String(length=255), nullable=True),
    sa.Column('simulated_value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_simulation_inputs_simulation', 'simulation_inputs', ['simulation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_simulation_inputs_simulation', table_name='simulation_inputs')
    op.drop_table('simulation_inputs')
    op.drop_index('idx_simulations_prediction', table_name='simulations')
    op.drop_table('simulations')
    op.drop_index('idx_shap_explanations_prediction', table_name='shap_explanations')
    op.drop_table('shap_explanations')
    op.drop_table('patient_inputs')
    op.drop_index('idx_predictions_user', table_name='predictions')
    op.drop_index('idx_predictions_risk_level', table_name='predictions')
    op.drop_index('idx_predictions_created', table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###

    op.execute('DROP EXTENSION IF EXISTS "pgcrypto"')
