"""Training paths and defaults."""

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
MODELS_DIR = REPO_ROOT / "models"

MODEL_FILENAME = "model.pkl"
PREPROCESSOR_FILENAME = "preprocessor.pkl"
METRICS_FILENAME = "metrics.json"
COMPARISON_FILENAME = "baseline_comparison.json"

LOGISTIC_REGRESSION_DIR = MODELS_DIR / "logistic_regression"
RANDOM_FOREST_DIR = MODELS_DIR / "random_forest"
XGBOOST_DIR = MODELS_DIR / "xgboost"
FINAL_MODEL_DIR = MODELS_DIR / "final"

LOGISTIC_REGRESSION_MODEL_PATH = LOGISTIC_REGRESSION_DIR / MODEL_FILENAME
LOGISTIC_REGRESSION_PREPROCESSOR_PATH = LOGISTIC_REGRESSION_DIR / PREPROCESSOR_FILENAME
LOGISTIC_REGRESSION_METRICS_PATH = LOGISTIC_REGRESSION_DIR / METRICS_FILENAME

RANDOM_FOREST_MODEL_PATH = RANDOM_FOREST_DIR / MODEL_FILENAME
RANDOM_FOREST_PREPROCESSOR_PATH = RANDOM_FOREST_DIR / PREPROCESSOR_FILENAME
RANDOM_FOREST_METRICS_PATH = RANDOM_FOREST_DIR / METRICS_FILENAME

XGBOOST_MODEL_PATH = XGBOOST_DIR / MODEL_FILENAME
XGBOOST_PREPROCESSOR_PATH = XGBOOST_DIR / PREPROCESSOR_FILENAME
XGBOOST_METRICS_PATH = XGBOOST_DIR / METRICS_FILENAME

BASELINE_COMPARISON_PATH = MODELS_DIR / COMPARISON_FILENAME
XGBOOST_EVALUATION_PATH = MODELS_DIR / "xgboost_evaluation.json"
FINAL_MODEL_SELECTION_PATH = MODELS_DIR / "final_model_selection.json"
MODEL_MANIFEST_PATH = MODELS_DIR / "model_manifest.json"

PRODUCTION_MODEL_PATH = MODELS_DIR / MODEL_FILENAME
PRODUCTION_PREPROCESSOR_PATH = MODELS_DIR / PREPROCESSOR_FILENAME
SHAP_BACKGROUND_FILENAME = "shap_background.npy"
PRODUCTION_SHAP_BACKGROUND_PATH = MODELS_DIR / SHAP_BACKGROUND_FILENAME

LOGISTIC_REGRESSION_MODEL_ID = "logistic_regression"
LOGISTIC_REGRESSION_MODEL_VERSION = "1.0.0"

RANDOM_FOREST_MODEL_ID = "random_forest"
RANDOM_FOREST_MODEL_VERSION = "1.0.0"

XGBOOST_MODEL_ID = "xgboost"
XGBOOST_MODEL_VERSION = "1.0.0"

MODEL_SOURCE_DIRS = {
    LOGISTIC_REGRESSION_MODEL_ID: LOGISTIC_REGRESSION_DIR,
    RANDOM_FOREST_MODEL_ID: RANDOM_FOREST_DIR,
    XGBOOST_MODEL_ID: XGBOOST_DIR,
}

MODEL_VERSIONS = {
    LOGISTIC_REGRESSION_MODEL_ID: LOGISTIC_REGRESSION_MODEL_VERSION,
    RANDOM_FOREST_MODEL_ID: RANDOM_FOREST_MODEL_VERSION,
    XGBOOST_MODEL_ID: XGBOOST_MODEL_VERSION,
}

SHAP_EXPLAINER_BY_MODEL = {
    LOGISTIC_REGRESSION_MODEL_ID: "linear",
    RANDOM_FOREST_MODEL_ID: "tree",
    XGBOOST_MODEL_ID: "tree",
}

PRODUCTION_MODEL_ID = LOGISTIC_REGRESSION_MODEL_ID

# Backward-compatible aliases used by T-205 artifacts.
MODEL_ID = LOGISTIC_REGRESSION_MODEL_ID
MODEL_VERSION = LOGISTIC_REGRESSION_MODEL_VERSION
